name: Publish to GitHub Pages

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  install-dependencies:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Download cached dependencies
        uses: actions/cache@v4
        id: cache
        with:
          path: node_modules
          key: deps-node-modules-${{ hashFiles('package-lock.json') }}

      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          npm install --package-lock-only
          npm ci

      - name: Unit tests
        run: npm run test:ci

      - name: Build code
        run: npm run build -- --base-href="/ng-london-bus-radar/"

      - name: List files
        run: ls -Rlh dist/ng-london-bus-radar

      - name: Save SHA
        run: |
          echo ${{ github.sha }} > "dist/ng-london-bus-radar/browser/sha.txt"
          cat "dist/ng-london-bus-radar/browser/sha.txt"

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist/ng-london-bus-radar/browser
